name: Collect Library Licenses

on:
  schedule:
    - cron: "0 2 * * 1" # Weekly on Monday
  workflow_dispatch:

permissions: {}

jobs:
  collect-licenses:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Collect library licenses
        uses: open-edge-platform/geti-ci/actions/collect-sbom-library@eee8dda846963533ec8b4498086f4432e3adea59
        with:
          path: .
